Redirect story pages to lower case slugs if the slug contains any capital latin letters
quintype/quintype-node-framework pull request #191
Opened 2021-01-21 05:20 UTC by EnKrypt

# Description

We want the feature to redirect story pages to their lower case equivalent if the slug contains any capital letters instead of showing a 404 today. This PR addresses that feature.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Run server locally, pass in a story URL with upper case slug. The server should redirect you to the URL having lowercase slug.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2021-01-21 05:21 UTC, EnKrypt commented
Tests to be added before merging

2021-01-21 08:25 UTC, EnKrypt commented
Could not run auto-formatter as there is no .prettierrc file in the repository.
The local formatter settings on my environment changes the entire file when formatted, so I intentionally saved without formatting.

2021-01-22 04:42 UTC, sivteck approved these changes

2021-01-22 05:39 UTC, sharangj approved these changes

2021-01-22 05:39 UTC, sharangj commented on test/integration/isomorphic-handler-test.js
> +    it("when enabled, redirects story slug with capital letters to lowercase slug URL", (done) => {
It is enabled

2021-01-22 05:39 UTC, sharangj commented on test/integration/isomorphic-handler-test.js
> +    it("when not enabled, story slug with capital letters gives a normal response", (done) => {
You need to cover a case when it is not story page too. This to protect ourselves from change on code later

2021-01-22 05:39 UTC, sharangj commented on server/handlers/isomorphic-handler.js
> +    const redirectToLowercaseSlugsValue = typeof redirectToLowercaseSlugs === 'function' ? redirectToLowercaseSlugs() : redirectToLowercaseSlugs;
Do you want to pass the config to the function? This will be helpful.

2021-01-22 05:40 UTC, sharangj requested changes
Sorry approved it by mistake

2021-01-25 05:36 UTC, sivteck approved these changes

2021-01-25 05:55 UTC, sharangj approved these changes
We need to do things before merging. One is a must and the other you can take a call.
1. Use the `config` variable in the `redirectToLowercaseSlugs` function call. (Not a must)
2. Please write an integration guide in developers.quintype.com. You can use the gh-pages branch in the [Malibu](https://github.com/quintype/malibu) github repository.  (This is a must)

Ill approve these changes for now but please dont forget the docs part.

2021-01-27 10:39 UTC, merged