Fix(cdn-caching): Added support for custom TTL cache values
quintype/quintype-node-framework pull request #245
Opened 2021-06-09 07:11 UTC by Deokumarjnu

# Description

Please include the summary of the change made. Please include the required context here. Please include the issue reference for the fix and the dependencies reference for the change.

Fixes # (issue-reference)

Dependencies # (dependency-issue-reference)

Documentation # (link to the corresponding documentation changes)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test Case A
- [ ] Test Case B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-06-09 08:20 UTC, EnKrypt approved these changes

2021-06-09 08:24 UTC, nandap4790 requested changes

2021-06-09 08:24 UTC, nandap4790 commented on server/amp/handlers/visual-stories-bookend.js
> +  { config, client, ttlCacheControl = "900" }
wouldn't `sMaxAge` or `ttl` be more relevant ?

2021-06-09 08:24 UTC, nandap4790 commented on server/handlers/cdn-caching.js
> +          "public,maxage=900,stale-while-revalidate=1000,stale-if-error=14400"
is this not required when cdn is akamai ?

2021-06-15 06:00 UTC, nandap4790 approved these changes

2021-06-15 06:02 UTC, merged