hardcode ttl of 10min for topic page
quintype/quintype-node-framework pull request #366
Opened 2023-05-11 12:48 UTC by ags1773

fixes https://github.com/quintype/page-builder/issues/2395

Context: platform doesn't have dedicated CDN cache keys for topic pages so FE was receiving stale data. So hardcoding a ttl of 10 min until platform makes a fix

2023-05-11 14:45 UTC, Athira001 requested changes

2023-05-12 03:46 UTC, ags1773 commented on server/handlers/cdn-caching.js
> +  if (req.path.startsWith("/topic")) {
pagetype need not be `tag-page`, it comes from the FE app

2023-05-12 04:05 UTC, Athira001 commented on server/handlers/cdn-caching.js
> +  if (req.path.startsWith("/topic")) {
in the Malibu framework, it is tag-page

2023-05-12 05:05 UTC, Athira001 approved these changes

2023-05-12 05:30 UTC, nandap4790 approved these changes

2023-05-12 06:07 UTC, merged