feat: add support to configure amp story page path through featureConfig
quintype/quintype-node-framework pull request #403
Opened 2023-11-28 08:45 UTC by cricket-lover

https://github.com/quintype/page-builder/issues/2737

This path has to be passed inside featureConfig. It can passed as a `function` or a `string`

```
featureConfig: {
    ampPageBasePath: () => "/amp"
}
```

2023-11-28 11:47 UTC, nandap4790 approved these changes

2023-11-28 12:01 UTC, Jeevan-Kishore commented on server/amp/helpers/get-amp-page-base-path.js
> +        ? opts.featureConfig.ampPageBasePath()
+1

2023-11-28 12:04 UTC, Jeevan-Kishore requested changes

2023-11-28 12:04 UTC, Jeevan-Kishore commented on server/amp/helpers/get-amp-page-base-path.js
> +    ampPageBasePath = configAmpPath || ampPageBasePath;
Return if true

2023-11-28 12:04 UTC, Jeevan-Kishore commented on server/amp/helpers/get-amp-page-base-path.js
> +  return ampPageBasePath;
Add this as default return

2023-11-28 12:47 UTC, VeenaYemmiganur approved these changes

2023-11-28 13:10 UTC, nandap4790 approved these changes

2023-11-29 06:03 UTC, ags1773 commented on server/amp/helpers/get-amp-page-base-path.js
> +  ampPageBasePath = typeof ampPageBasePath === "function" ? ampPageBasePath() : ampPageBasePath;
You'll need to pass `config` to `ampPageBasePath` function.. Madrid will need config to access pagebuilder config

Madrid code:
![Screenshot 2023-11-29 at 11 33 21 AM](https://github.com/quintype/quintype-node-framework/assets/27222520/450af40c-eb25-4706-880e-277100ffbe02)

2023-12-01 08:07 UTC, merged